# Python Secrets Demo

name: Python Secrets Demo

on: push

jobs:
  secret-demo:
    runs-on: ubuntu-22.04

    env:
      MY_API_KEY: ${{ secrets.MY_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run:  | 
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Execute Python Script
        run:  | 
            python app.py