# .github/workflows/hello.yml

name: Hello Workflow

on: push

jobs:
  hello-job:
    runs-on: ubuntu-22.04

    steps:
      - name: Print Hello
        run: echo "Hello Github Actions"

      - name: Print Date ana Time
        run: date

      - name: Print OS
        run: echo "The operating system is ${{ runner.os }}"

      - name: Print branh name
        run: echo "The current branch is ${{ github.ref_name }}"

  
